// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PublicTransit.Infrastructure;

#nullable disable

namespace PublicTransit.Infrastructure.Migrations
{
    [DbContext(typeof(PublicTransitContext))]
    [Migration("20251112193603_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.FoodSourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailableYearRound")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NutritionalValue")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("FoodSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsAvailableYearRound = false,
                            Name = "Нектар квітів",
                            NutritionalValue = 85,
                            Type = "Нектар"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsAvailableYearRound = true,
                            Name = "Органічні відходи",
                            NutritionalValue = 45,
                            Type = "Органіка"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsAvailableYearRound = true,
                            Name = "Кров тварин",
                            NutritionalValue = 95,
                            Type = "Кров"
                        });
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.HabitatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InsectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("InsectId")
                        .IsUnique();

                    b.ToTable("Habitats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Climate = "Помірно-континентальний",
                            Humidity = 65,
                            InsectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Location = "Київ, Голосіївський парк",
                            Temperature = 18.5
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Climate = "Помірний",
                            Humidity = 70,
                            InsectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Location = "Львів, ботанічний сад",
                            Temperature = 16.0
                        });
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.InsectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FoodSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HabitatId")
                        .HasColumnType("uuid");

                    b.Property<int>("Legs")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FoodSourceId");

                    b.HasIndex("Name");

                    b.ToTable("Insects", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.InsectPredatorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefenseMechanism")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FirstEncounterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InsectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PredatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PredatorId");

                    b.HasIndex("InsectId", "PredatorId")
                        .IsUnique();

                    b.ToTable("InsectPredators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaabbbb-cccc-dddd-eeee-111122223333"),
                            DefenseMechanism = "Швидкий політ",
                            FirstEncounterDate = new DateTime(2025, 10, 13, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(8018),
                            InsectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PredatorId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            RiskLevel = 7
                        },
                        new
                        {
                            Id = new Guid("bbbbcccc-dddd-eeee-ffff-222233334444"),
                            DefenseMechanism = "Маневрування",
                            FirstEncounterDate = new DateTime(2025, 9, 28, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(8541),
                            InsectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PredatorId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            RiskLevel = 6
                        },
                        new
                        {
                            Id = new Guid("ccccdddd-eeee-ffff-aaaa-333344445555"),
                            DefenseMechanism = "Павутина",
                            FirstEncounterDate = new DateTime(2025, 9, 13, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(8561),
                            InsectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PredatorId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            RiskLevel = 8
                        },
                        new
                        {
                            Id = new Guid("ddddeeee-ffff-aaaa-bbbb-444455556666"),
                            DefenseMechanism = "Отрута",
                            FirstEncounterDate = new DateTime(2025, 10, 23, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(8861),
                            InsectId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            PredatorId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            RiskLevel = 5
                        });
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.PredatorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HuntingSuccess")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Size")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Species");

                    b.ToTable("Predators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            HuntingSuccess = 65,
                            Name = "Горобець",
                            Size = 14.5,
                            Species = "Птах"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            HuntingSuccess = 85,
                            Name = "Богомол",
                            Size = 8.0,
                            Species = "Комаха"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            HuntingSuccess = 70,
                            Name = "Ящірка звичайна",
                            Size = 18.0,
                            Species = "Рептилія"
                        });
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.FlyModel", b =>
                {
                    b.HasBaseType("PublicTransit.Infrastructure.Models.InsectModel");

                    b.Property<bool>("CanHover")
                        .HasColumnType("boolean");

                    b.Property<int>("FlightSpeed")
                        .HasColumnType("integer");

                    b.Property<double>("WingSpan")
                        .HasColumnType("decimal(5,2)");

                    b.ToTable("Flies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 11, 12, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(691),
                            FoodSourceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Legs = 6,
                            Name = "Муха звичайна",
                            CanHover = true,
                            FlightSpeed = 8,
                            WingSpan = 3.5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 11, 12, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(2108),
                            FoodSourceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Legs = 6,
                            Name = "Дрозофіла",
                            CanHover = false,
                            FlightSpeed = 5,
                            WingSpan = 1.2
                        });
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.SpiderModel", b =>
                {
                    b.HasBaseType("PublicTransit.Infrastructure.Models.InsectModel");

                    b.Property<bool>("IsPoisonous")
                        .HasColumnType("boolean");

                    b.Property<int>("VenomPotency")
                        .HasColumnType("integer");

                    b.Property<double>("WebStrength")
                        .HasColumnType("decimal(5,2)");

                    b.ToTable("Spiders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 11, 12, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(2584),
                            Legs = 8,
                            Name = "Павук-хрестовик",
                            IsPoisonous = false,
                            VenomPotency = 2,
                            WebStrength = 75.5
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 11, 12, 19, 36, 2, 516, DateTimeKind.Utc).AddTicks(3115),
                            Legs = 8,
                            Name = "Чорна вдова",
                            IsPoisonous = true,
                            VenomPotency = 9,
                            WebStrength = 90.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicTransit.Infrastructure.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.HabitatModel", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.InsectModel", "Insect")
                        .WithOne("Habitat")
                        .HasForeignKey("PublicTransit.Infrastructure.Models.HabitatModel", "InsectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Insect");
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.InsectModel", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.FoodSourceModel", "FoodSource")
                        .WithMany("Insects")
                        .HasForeignKey("FoodSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FoodSource");
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.InsectPredatorModel", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.InsectModel", "Insect")
                        .WithMany("InsectPredators")
                        .HasForeignKey("InsectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicTransit.Infrastructure.Models.PredatorModel", "Predator")
                        .WithMany("InsectPredators")
                        .HasForeignKey("PredatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insect");

                    b.Navigation("Predator");
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.FlyModel", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.InsectModel", null)
                        .WithOne()
                        .HasForeignKey("PublicTransit.Infrastructure.Models.FlyModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.SpiderModel", b =>
                {
                    b.HasOne("PublicTransit.Infrastructure.Models.InsectModel", null)
                        .WithOne()
                        .HasForeignKey("PublicTransit.Infrastructure.Models.SpiderModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.FoodSourceModel", b =>
                {
                    b.Navigation("Insects");
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.InsectModel", b =>
                {
                    b.Navigation("Habitat");

                    b.Navigation("InsectPredators");
                });

            modelBuilder.Entity("PublicTransit.Infrastructure.Models.PredatorModel", b =>
                {
                    b.Navigation("InsectPredators");
                });
#pragma warning restore 612, 618
        }
    }
}
